### ISSUE TITLE
React as a dependency

### ISSUE THREAD

**Issue by Ppjet6** [markfinger/react-render#6]
I am not sure I understand why react is currently required as a `devDependency`? Is this supposed to be compiled/minified before being used or..?

**Comment by markfinger** [comment]
`devDependencies` are intended when developing the package itself. In the context of this package, the version specified in `devDependencies` is only used to run the tests.

React's also listed in `peerDependencies` so that downstream users can control the version of React that's used. Allowing users to control the versions is fairly important, so that the front-end and back-end versions match. If you pre-rendered with an older versions of React, it would generate markup that newer versions would complain about when they mounted over it.

**Comment by Ppjet6** [comment]
Alright, ok. I didn't notice that you updated the `peerDependencies` to `>= 0.14`, that's something I forgot in my PR. Thank you for the clarification.
